### PR TITLE
Hiding the file upload button using css

### PR DESCRIPTION
**Pull request by mtwn105**
Fixing #44

### CODE REVIEW

**Comment by simonbesteiro** [comment]
@watchoutfreedom working on a PR improving this one maybe can we merge it today to fit on hackotoberfest?

**Comment by watchoutfreedom** [comment]
Ok!

**Comment by simonbesteiro** [comment]
great! give me half an hour- 1 hour

**Comment by simonbesteiro** [comment]
@watchoutfreedom part 1 done here https://github.com/helpbuttons/hb-front/pull/70 working on part 2

I will suggest merging this one first and then the second one after 

friendly reminder, about hackotoberfest labels

**Comment by watchoutfreedom** [comment]
already merged part 1

**Comment by simonbesteiro** [comment]
@watchoutfreedom I have been trying to link the Class but it gets a little bit over my current knowledge. Even though I inserted a component which list images, currently is hardcoded but you will be able to iterate the answer from the class and make it dynamic, hope it gets useful
 https://github.com/helpbuttons/hb-front/pull/71

**Comment by watchoutfreedom** [comment]
Thanks! merged !

**Pull request closed without merging**
